apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: ana2
        - name: MYSQL_PASSWORD
          value: daniel
        - name: MYSQL_ROOT_PASSWORD
          value: "123456789"
        - name: MYSQL_USER
          value: daniel
        - image: jorged104/apiserver:database
        name: database
        ports:
        - containerPort: 3306
        resources: {}
      
