version: '3'
services:
  webserver:
    container_name: apiserver
    image: jorged104/apiserver   
    build: ./API/   
    depends_on:
      - database    
    ports:
      - "3000:3000"   
    environment:
      MYSQL_DATABASE: ana2
      MYSQL_USER: daniel
      MYSQL_PASSWORD: daniel
    restart: on-failure
  front:
    container_name: front
    image: jorged104/front 
    build: ./FRONT/
    depends_on:
      - webserver     
    ports:
      - "80:4000"      
  database:
    container_name: database
    image: jorged104/apiserver:database
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ana2
      MYSQL_ROOT_PASSWORD: 123456789
      MYSQL_USER: daniel
      MYSQL_PASSWORD: daniel

 
